# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KM0lX8iumCvaklzP1MaNwSYIxxO0bwkx
"""

from google.colab import files 
data = files.upload()

import pandas as pd
import plotly.express as px

dataFrame = pd.read_csv("Copy+of+data+-+data.csv")
chart = px.scatter(dataFrame, x = "date", y = "cases", color = "country")
chart.show()